### ISSUE TITLE
Refactoring concerns

### ISSUE THREAD

**Issue by kadirsefaunal** [nuriu/cemiyet-backend#33]
The following items will be edited within the scope of this work.

- [ ] More control over the handlers
   - [ ] Return types of command handlers
   - [ ] Http status codes returned from commands
- [ ] MediatR 8.0 exception handlers
   - We can probably handle previous concern(s) with this.
- [ ] Checking C# 8 features for suitable improvements

**Comment by nuriu** [comment]
I edited list with more generic one, with further potential improvements in mind.

If it's okay with you, we should proceed that way. Any further recommendations is appreciated.

**Comment by nuriu** [comment]
[MediatR 8.0 released](https://jimmybogard.com/mediatr-8-0-released/) and added new built-in pipeline behaviors for [handling exceptions](https://github.com/jbogard/mediatr/wiki#exceptions-handling).

We should try some use-cases and maybe replace current exception filters with these new behaviors.

Also we can look into C# 8 features for suitable improvements.

I added these two concerns to the main list and planning to go over them next week. Can you deal with some of them anytime soon @kadirsefaunal?
